# Generated by Django 5.0.6 on 2024-06-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('image', models.FileField(max_length=60, null=True, upload_to='carousel/')),
            ],
        ),
    ]
