# Generated by Django 5.0.6 on 2024-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='save',
            field=models.IntegerField(null=True),
        ),
    ]
