# Generated by Django 5.0.6 on 2024-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
