# Generated by Django 5.0.6 on 2024-06-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='save',
            field=models.IntegerField(max_length=60, null=True),
        ),
    ]
