# Generated by Django 5.0.6 on 2024-06-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='save',
            field=models.IntegerField(null=True),
        ),
    ]
